version: '3.8'

services:
  # Backend API Service
  backend:
    build: ./backend
    ports:
      - "3001:3000" # Map host port 3001 to container port 3000
    env_file:
      - ./backend/.env # Use the existing .env file
    environment:
      # Override MONGO_URI to connect to the 'mongo' service
      - MONGO_URI=mongodb://mongo:27017/loopjs
    depends_on:
      - mongo

  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "80:80" # Map host port 80 to container port 80

  # MongoDB Service
  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db # Persist database data

volumes:
  mongo-data: