# Google App Engine configuration for Wordful deployment
runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  MONGO_URI: "mongodb+srv://wordful-user:${sm://mongodb-password}@wordful-cluster.mongodb.net/wordful-production?retryWrites=true&w=majority"
  SESSION_SECRET: "${sm://session-secret}"
  JWT_SECRET: "${sm://jwt-secret}"
  JWT_ACCESS_TOKEN_EXPIRATION: "15m"
  JWT_REFRESH_TOKEN_EXPIRATION: "24h"
  ALLOWED_ORIGINS: "https://wordful.app"
  LOG_LEVEL: "info"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  WS_HEARTBEAT_INTERVAL: "30000"
  WS_CONNECTION_TIMEOUT: "60000"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 3
  max_concurrent_requests: 50

inbound_services:
- warmup

health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 300