
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Linux - 6.1.147 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/c++ 
      Build flags: -static;-static-libgcc;-static-libstdc++;-O3;-DNDEBUG;-s
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is Clang, found in:
        /workspace/clients/qt-client/build-linux/CMakeFiles/3.31.6/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "/usr/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "/workspace/clients/qt-client/build-linux/CMakeFiles/CMakeScratch/TryCompile-nbFltU"
      binary: "/workspace/clients/qt-client/build-linux/CMakeFiles/CMakeScratch/TryCompile-nbFltU"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/bin/clang-scan-deps-20"
      CMAKE_CXX_FLAGS: "-static -static-libgcc -static-libstdc++ -O3 -DNDEBUG -s"
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "-static -static-libgcc -static-libstdc++"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/workspace/clients/qt-client/build-linux/CMakeFiles/CMakeScratch/TryCompile-nbFltU'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_cd79c/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_cd79c.dir/build.make CMakeFiles/cmTC_cd79c.dir/build
        gmake[1]: Entering directory '/workspace/clients/qt-client/build-linux/CMakeFiles/CMakeScratch/TryCompile-nbFltU'
        Building CXX object CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o
        /usr/bin/c++   -static -static-libgcc -static-libstdc++ -O3 -DNDEBUG -s    -v -MD -MT CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o -MF CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o.d -o CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o -c /usr/share/cmake-3.31/Modules/CMakeCXXCompilerABI.cpp
        Ubuntu clang version 20.1.2 (0ubuntu1)
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        InstalledDir: /usr/lib/llvm-20/bin
        Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14
        Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14
        Candidate multilib: .;@m64
        Selected multilib: .;@m64
        c++: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
        c++: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
        c++: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
         (in-process)
         "/usr/lib/llvm-20/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -static-define -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/workspace/clients/qt-client/build-linux/CMakeFiles/CMakeScratch/TryCompile-nbFltU -v -fcoverage-compilation-dir=/workspace/clients/qt-client/build-linux/CMakeFiles/CMakeScratch/TryCompile-nbFltU -resource-dir /usr/lib/llvm-20/lib/clang/20 -dependency-file CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o.d -MT CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o -sys-header-deps -D NDEBUG -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/x86_64-linux-gnu/c++/14 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/backward -internal-isystem /usr/lib/llvm-20/lib/clang/20/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/14/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -fdeprecated-macro -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -vectorize-loops -vectorize-slp -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o -x c++ /usr/share/cmake-3.31/Modules/CMakeCXXCompilerABI.cpp
        clang -cc1 version 20.1.2 based upon LLVM 20.1.2 default target x86_64-pc-linux-gnu
        ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/14/../../../../x86_64-linux-gnu/include"
        ignoring nonexistent directory "/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14
         /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/x86_64-linux-gnu/c++/14
         /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/backward
         /usr/lib/llvm-20/lib/clang/20/include
         /usr/local/include
         /usr/include/x86_64-linux-gnu
         /usr/include
        End of search list.
        Linking CXX executable cmTC_cd79c
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cd79c.dir/link.txt --verbose=1
        Ubuntu clang version 20.1.2 (0ubuntu1)
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        InstalledDir: /usr/lib/llvm-20/bin
        Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14
        Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14
        Candidate multilib: .;@m64
        Selected multilib: .;@m64
         "/usr/bin/ld" -s -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -static -o cmTC_cd79c /lib/x86_64-linux-gnu/crt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/14/crtbeginT.o -L/usr/lib/gcc/x86_64-linux-gnu/14 -L/usr/lib/gcc/x86_64-linux-gnu/14/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib -v CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm --start-group -lgcc -lgcc_eh -lc --end-group /usr/lib/gcc/x86_64-linux-gnu/14/crtend.o /lib/x86_64-linux-gnu/crtn.o
        GNU ld (GNU Binutils for Ubuntu) 2.44
        /usr/bin/c++ -static -static-libgcc -static-libstdc++ -O3 -DNDEBUG -s  -static -static-libgcc -static-libstdc++ -v -Wl,-v CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o -o cmTC_cd79c
        gmake[1]: Leaving directory '/workspace/clients/qt-client/build-linux/CMakeFiles/CMakeScratch/TryCompile-nbFltU'
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:182 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Parsed CXX implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14]
          add: [/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/x86_64-linux-gnu/c++/14]
          add: [/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/backward]
          add: [/usr/lib/llvm-20/lib/clang/20/include]
          add: [/usr/local/include]
          add: [/usr/include/x86_64-linux-gnu]
          add: [/usr/include]
        end of search list found
        collapse include dir [/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14] ==> [/usr/include/c++/14]
        collapse include dir [/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/x86_64-linux-gnu/c++/14] ==> [/usr/include/x86_64-linux-gnu/c++/14]
        collapse include dir [/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/backward] ==> [/usr/include/c++/14/backward]
        collapse include dir [/usr/lib/llvm-20/lib/clang/20/include] ==> [/usr/lib/llvm-20/lib/clang/20/include]
        collapse include dir [/usr/local/include] ==> [/usr/local/include]
        collapse include dir [/usr/include/x86_64-linux-gnu] ==> [/usr/include/x86_64-linux-gnu]
        collapse include dir [/usr/include] ==> [/usr/include]
        implicit include dirs: [/usr/include/c++/14;/usr/include/x86_64-linux-gnu/c++/14;/usr/include/c++/14/backward;/usr/lib/llvm-20/lib/clang/20/include;/usr/local/include;/usr/include/x86_64-linux-gnu;/usr/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?))("|,| |$)]
        ignore line: [Change Dir: '/workspace/clients/qt-client/build-linux/CMakeFiles/CMakeScratch/TryCompile-nbFltU']
        ignore line: []
        ignore line: [Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_cd79c/fast]
        ignore line: [/usr/bin/gmake  -f CMakeFiles/cmTC_cd79c.dir/build.make CMakeFiles/cmTC_cd79c.dir/build]
        ignore line: [gmake[1]: Entering directory '/workspace/clients/qt-client/build-linux/CMakeFiles/CMakeScratch/TryCompile-nbFltU']
        ignore line: [Building CXX object CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o]
        ignore line: [/usr/bin/c++   -static -static-libgcc -static-libstdc++ -O3 -DNDEBUG -s    -v -MD -MT CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o -MF CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o.d -o CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o -c /usr/share/cmake-3.31/Modules/CMakeCXXCompilerABI.cpp]
        ignore line: [Ubuntu clang version 20.1.2 (0ubuntu1)]
        ignore line: [Target: x86_64-pc-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /usr/lib/llvm-20/bin]
        ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14]
        ignore line: [Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        ignore line: [c++: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]]
        ignore line: [c++: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]]
        ignore line: [c++: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]]
        ignore line: [ (in-process)]
        ignore line: [ "/usr/lib/llvm-20/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -static-define -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/workspace/clients/qt-client/build-linux/CMakeFiles/CMakeScratch/TryCompile-nbFltU -v -fcoverage-compilation-dir=/workspace/clients/qt-client/build-linux/CMakeFiles/CMakeScratch/TryCompile-nbFltU -resource-dir /usr/lib/llvm-20/lib/clang/20 -dependency-file CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o.d -MT CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o -sys-header-deps -D NDEBUG -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/x86_64-linux-gnu/c++/14 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/backward -internal-isystem /usr/lib/llvm-20/lib/clang/20/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/14/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -fdeprecated-macro -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -vectorize-loops -vectorize-slp -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o -x c++ /usr/share/cmake-3.31/Modules/CMakeCXXCompilerABI.cpp]
        ignore line: [clang -cc1 version 20.1.2 based upon LLVM 20.1.2 default target x86_64-pc-linux-gnu]
        ignore line: [ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/14/../../../../x86_64-linux-gnu/include"]
        ignore line: [ignoring nonexistent directory "/include"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14]
        ignore line: [ /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/x86_64-linux-gnu/c++/14]
        ignore line: [ /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/backward]
        ignore line: [ /usr/lib/llvm-20/lib/clang/20/include]
        ignore line: [ /usr/local/include]
        ignore line: [ /usr/include/x86_64-linux-gnu]
        ignore line: [ /usr/include]
        ignore line: [End of search list.]
        ignore line: [Linking CXX executable cmTC_cd79c]
        ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cd79c.dir/link.txt --verbose=1]
        ignore line: [Ubuntu clang version 20.1.2 (0ubuntu1)]
        ignore line: [Target: x86_64-pc-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /usr/lib/llvm-20/bin]
        ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14]
        ignore line: [Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        link line: [ "/usr/bin/ld" -s -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -static -o cmTC_cd79c /lib/x86_64-linux-gnu/crt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/14/crtbeginT.o -L/usr/lib/gcc/x86_64-linux-gnu/14 -L/usr/lib/gcc/x86_64-linux-gnu/14/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib -v CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm --start-group -lgcc -lgcc_eh -lc --end-group /usr/lib/gcc/x86_64-linux-gnu/14/crtend.o /lib/x86_64-linux-gnu/crtn.o]
          arg [/usr/bin/ld] ==> ignore
          arg [-s] ==> ignore
          arg [-zrelro] ==> ignore
          arg [--hash-style=gnu] ==> ignore
          arg [--build-id] ==> ignore
          arg [--eh-frame-hdr] ==> ignore
          arg [-m] ==> ignore
          arg [elf_x86_64] ==> ignore
          arg [-static] ==> ignore
          arg [-o] ==> ignore
          arg [cmTC_cd79c] ==> ignore
          arg [/lib/x86_64-linux-gnu/crt1.o] ==> obj [/lib/x86_64-linux-gnu/crt1.o]
          arg [/lib/x86_64-linux-gnu/crti.o] ==> obj [/lib/x86_64-linux-gnu/crti.o]
          arg [/usr/lib/gcc/x86_64-linux-gnu/14/crtbeginT.o] ==> obj [/usr/lib/gcc/x86_64-linux-gnu/14/crtbeginT.o]
          arg [-L/usr/lib/gcc/x86_64-linux-gnu/14] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/14]
          arg [-L/usr/lib/gcc/x86_64-linux-gnu/14/../../../../lib64] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/14/../../../../lib64]
          arg [-L/lib/x86_64-linux-gnu] ==> dir [/lib/x86_64-linux-gnu]
          arg [-L/lib/../lib64] ==> dir [/lib/../lib64]
          arg [-L/usr/lib/x86_64-linux-gnu] ==> dir [/usr/lib/x86_64-linux-gnu]
          arg [-L/usr/lib/../lib64] ==> dir [/usr/lib/../lib64]
          arg [-L/lib] ==> dir [/lib]
          arg [-L/usr/lib] ==> dir [/usr/lib]
          arg [-v] ==> ignore
          arg [CMakeFiles/cmTC_cd79c.dir/CMakeCXXCompilerABI.cpp.o] ==> ignore
          arg [-lstdc++] ==> lib [stdc++]
          arg [-lm] ==> lib [m]
          arg [--start-group] ==> ignore
          arg [-lgcc] ==> lib [gcc]
          arg [-lgcc_eh] ==> lib [gcc_eh]
          arg [-lc] ==> lib [c]
          arg [--end-group] ==> ignore
          arg [/usr/lib/gcc/x86_64-linux-gnu/14/crtend.o] ==> obj [/usr/lib/gcc/x86_64-linux-gnu/14/crtend.o]
          arg [/lib/x86_64-linux-gnu/crtn.o] ==> obj [/lib/x86_64-linux-gnu/crtn.o]
        linker tool for 'CXX': /usr/bin/ld
        remove lib [gcc_eh]
        collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/14] ==> [/usr/lib/gcc/x86_64-linux-gnu/14]
        collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/14/../../../../lib64] ==> [/usr/lib64]
        collapse library dir [/lib/x86_64-linux-gnu] ==> [/lib/x86_64-linux-gnu]
        collapse library dir [/lib/../lib64] ==> [/lib64]
        collapse library dir [/usr/lib/x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
        collapse library dir [/usr/lib/../lib64] ==> [/usr/lib64]
        collapse library dir [/lib] ==> [/lib]
        collapse library dir [/usr/lib] ==> [/usr/lib]
        implicit libs: [stdc++;m;gcc;c]
        implicit objs: [/lib/x86_64-linux-gnu/crt1.o;/lib/x86_64-linux-gnu/crti.o;/usr/lib/gcc/x86_64-linux-gnu/14/crtbeginT.o;/usr/lib/gcc/x86_64-linux-gnu/14/crtend.o;/lib/x86_64-linux-gnu/crtn.o]
        implicit dirs: [/usr/lib/gcc/x86_64-linux-gnu/14;/usr/lib64;/lib/x86_64-linux-gnu;/lib64;/usr/lib/x86_64-linux-gnu;/lib;/usr/lib]
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "/usr/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Running the CXX compiler's linker: "/usr/bin/ld" "-v"
      GNU ld (GNU Binutils for Ubuntu) 2.44
...
